#!/bin/bash

if [[ "$hlp" = true ]] ; then
	echo ""
	echo "DESCRIPTION"
	echo "-------------------"
	echo "This script runs the full Qiime2 pipeline"
	echo "You need to set configurations in config.txt,"
	echo "which is created with optional_analyses.txt"
	echo "when waterway is first run using the command"
	echo '"waterway .", without the quotes.'
	echo ""
	echo "USAGE"
	echo "-------------------"
	echo "[path_to_waterway]/waterway.bash [path_to_dir_containing_configs] {options}"
	echo "Note: the path_to_dir is mandatory when using options"
	echo ""
	echo "If add_to_bashrc.bash has already been run, then you can run waterway via"
	echo "the command:"
	echo "waterway [path_to_dir_containing_configs] {options}"
	echo ""
	echo "OPTIONS"
	echo "-------------------"
	echo -e "-M\tGenerate manifest file from files in filepath (in config.txt)"
	echo -e "-m\tUse manifest file to import sequences, as specified in the config file"
	echo -e "-v\tVerbose script output"
	echo -e "-t\tTest the progress flags and exit before executing any real qiime commands"
	echo -e "-T\tFilter the table.qza and rep-seqs.qza in the outputs folder by metadata file (run once to generate the filter-inputs directory)"
	echo -e "-l\tEnable logging to a log file that is made where this script is"
	echo -e "-f\tShow the exact list of functions used in this script and their output files"
	echo -e "-c\tTrain a greengenes 13_5 99% coverage otu classifier from variables supplied in config.txt"
	echo -e "-r\tReplaces underscores with hyphens from filenames that match a pattern that includes underscores to replace."
	echo -e "-F\tFilters the table.qza and rep-seqs.qza by metadata files located in metadata/filter_inputs/"
	echo -e "-s\tCreate subsets from metadata files in filter_inputs/, then analyze all subsets"
	echo -e "--version Show the currently running Qiime2 and waterway version numbers"
	echo -e "--install-deicode Install the DEICODE Qiime2 plugin"
	echo -e "--install-picrust Install the Picrust2 Qiime2 plugin"
	echo -e "--add-waterway Adds the waterway command to .bashrc, allowing for use of the command: waterway"
	echo -e "-h\tShow this help dialogue"
	echo ""
	echo "For more information on how to use waterway, refer to the tutorial at:"
	echo "http://marqueslab.erc.monash.edu/home/michael/waterway_docs/QYyBgctVnjnFvSFij7qJrMul6/tut.html"
	exit 0
fi